FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build-env
WORKDIR /app

# RUN apt-get update && apt-get install
# RUN apt update && apt install -y npm
# Copy everything
COPY . ./

# Restore as distinct layers
COPY *.csproj ./
RUN dotnet restore
# Build and publish a release
RUN dotnet publish -c Release# -o out

# Build runtime image
FROM mcr.microsoft.com/dotnet/aspnet:6.0
# WORKDIR /app
# COPY --from=build-env /app/out .
COPY bin/Release/net6.0/publish/ App/
COPY ClientApp/build/ App/ClientApp/build/
WORKDIR /App
EXPOSE 5000
ENTRYPOINT ["dotnet", "RandomSongSearchEngine.dll"]