FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build-env
WORKDIR /app
RUN apt-get update && apt-get install -y nodejs
COPY . ./
COPY *.csproj ./
RUN dotnet restore
RUN dotnet publish -c Release -o out

FROM mcr.microsoft.com/dotnet/aspnet:6.0
COPY --from=build-env /app/out/ App/
COPY --from=build-env /app/ClientApp/build/ App/ClientApp/build/
WORKDIR /App
EXPOSE 5000
ENTRYPOINT ["dotnet", "RandomSongSearchEngine.dll"]